server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://haleha-db-1.cekteqc93q13.eu-west-3.rds.amazonaws.com:3306/halehabank
    username: admin
    password: adMinHaleha2014
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
